# Docker Image
image: bkormann/hm-gcc-cmocka:8.5.1

stages:
  - build
  - test
  - metric


buildVersuch03:
  stage: build
  script:
    - cd Praktikum/Versuch03
    - mkdir -p bin
    - mkdir -p build
    - gcc -c ti_bmp.c -o build/ti_bmp.o
    - gcc -c test/versuch01_test.c -I. -o build/versuch01_test.o
    - gcc -c test/versuch02_test.c -I. -o build/versuch02_test.o
    - gcc -c test/versuch03_test.c -I. -o build/versuch03_test.o
    - gcc build/versuch01_test.o build/ti_bmp.o -o bin/versuch01_test -lcmocka -lm
    - gcc build/versuch02_test.o build/ti_bmp.o -o bin/versuch02_test -lcmocka -lm
    - gcc build/versuch03_test.o build/ti_bmp.o -o bin/versuch03_test -lcmocka -lm
  cache:
    paths:
      - Praktikum/Versuch03/bin

testVersuch03:
  stage: test
  needs: [buildVersuch03]
  script:
    - cd Praktikum/Versuch03
    - touch bin/report01.xml ; rm bin/report01.xml
    - CMOCKA_MESSAGE_OUTPUT=XML CMOCKA_XML_FILE=bin/report01.xml bin/versuch01_test    
    - touch bin/report02.xml ; rm bin/report02.xml
    - CMOCKA_MESSAGE_OUTPUT=XML CMOCKA_XML_FILE=bin/report02.xml bin/versuch02_test
    - touch bin/report03.xml ; rm bin/report03.xml
    - CMOCKA_MESSAGE_OUTPUT=XML CMOCKA_XML_FILE=bin/report03.xml bin/versuch03_test

  cache:
    paths:
      - Praktikum/Versuch03/bin
  artifacts:
    when: always
    reports:
      junit: Praktikum/Versuch03/bin/report*.xml
      
docVersuch03:
  stage: metric
  script:
    - cd Praktikum/Versuch03
    - cloc --by-percent cmb *.h *.c > clocVersuch03.txt
  artifacts:
    paths:
      - Praktikum/Versuch03/clocVersuch03.txt
